# Generated by Django 4.2.25 on 2025-11-04 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('residential_address', models.TextField()),
                ('languages_spoken', models.CharField(max_length=200)),
                ('preferred_position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=20)),
                ('current_school', models.CharField(blank=True, max_length=200, null=True)),
                ('current_class', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('has_medical_condition', models.BooleanField(default=False)),
                ('medical_condition_details', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC')], max_length=2)),
                ('has_physical_disability', models.BooleanField(default=False)),
                ('physical_disability_details', models.TextField(blank=True, null=True)),
                ('parent_full_name', models.CharField(max_length=200)),
                ('parent_relationship', models.CharField(max_length=50)),
                ('parent_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('parent_alternative_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_home_address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('consent_participate', models.BooleanField(default=False)),
                ('consent_information_accurate', models.BooleanField(default=False)),
                ('consent_liability_release', models.BooleanField(default=False)),
                ('consent_abide_rules', models.BooleanField(default=False)),
                ('parent_signature', models.CharField(max_length=200)),
                ('player_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('registration_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_clearance', models.BooleanField(default=False)),
                ('official_comments', models.TextField(blank=True, null=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='registrations.lga')),
                ('state_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='registrations.state')),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='registrations.state'),
        ),
        migrations.AlterUniqueTogether(
            name='lga',
            unique_together={('name', 'state')},
        ),
    ]
